version: "3"

services:
  postgres:
    container_name: postgres
    image: postgres:latest
    ports:
      - "5433:5433"
    environment:
      # POSTGRES_PORT: 5432
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: e-commerce_db
    networks:
      - backend

  nestjs:
    build:
      context: .
    container_name: nestjs
    ports:
      - "3000:3000"
    networks:
      - backend
    depends_on:
      - postgres
    environment:
      - NODE_ENV=production
    volumes:
      - ./config.yaml:/app/dist/config.yaml

networks:
  backend:
